services:
  test_k3d:
    container_name: test_k3d
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash ./run.sh test k3d && curl http://k3d-test-server-0
  test_kind:
    container_name: test_kind
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash ./run.sh test kind && curl http://k3d-test-server-0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
