name: dagger_hackathon  # Name of the workflow

on:
  pull_request:
    branches: [main]  # target branch of the PR
    types: [opened, synchronize, reopened]

jobs:
  dagger-run-unit-tests:
    runs-on: ubuntu-latest  # Define the runner environment

    env:
      GITHUB_TOKEN: ${{ secrets.DAGGER_HACKATHON_GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CURRENT_BRANCH: ${{ github.head_ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dagger CLI
        run: |
          curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Dagger Run Unit Tests
        working-directory: docs/dagger/dagger-hackathon/
        run: |
          export AZURE_OPENAI_API_KEY="${OPENAI_API_KEY}"
          export AZURE_OPENAI_ENDPOINT="https://vdfvdf.openai.azure.com/"
          dagger call debug-unit-test-agent --directory-arg="." \
          --github-token=GITHUB_TOKEN \
          --github-branch="feature/dagger_hackathon_git_action" \
          --github-repo="codetocloudorg/platform-engineering" \
          --azure-model="gpt-4o" \
          --azure-endpoint="${AZURE_OPENAI_ENDPOINT}" \
          --azure-api-key="${AZURE_OPENAI_API_KEY}"