name: dagger_hackathon

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  dagger-run-unit-tests:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.DAGGER_HACKATHON_GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CURRENT_BRANCH: ${{ github.head_ref }}
      CURRENT_REPO: ${{ github.repository }}
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      AZURE_OPENAI_ENDPOINT: https://vdfvdf.openai.azure.com/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dagger CLI
        run: |
          curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create .env file
        working-directory: docs/dagger/dagger-hackathon/
        run: |
          cat <<EOF > .env
          OPENAI_BASE_URL=${AZURE_OPENAI_ENDPOINT}
          OPENAI_MODEL=gpt-4o
          OPENAI_API_KEY=${OPENAI_API_KEY}
          OPENAI_AZURE_VERSION=2024-12-01-preview
          EOF

      - name: Dagger Run Unit Tests
        working-directory: docs/dagger/dagger-hackathon/
        run: |
          export AZURE_OPENAI_API_KEY="${OPENAI_API_KEY}"
          export GITHUB_TOKEN="${GITHUB_TOKEN}"
          export DAGGER_CLOUD_TOKEN="${DAGGER_CLOUD_TOKEN}"
          dagger call \
            --source="." \
            --github_branch="${CURRENT_BRANCH}" \
            --github_repo="${CURRENT_REPO}" \
            --github_token=GITHUB_TOKEN \
            --azure_openai_api_key=AZURE_OPENAI_API_KEY \
            --azure_openai_endpoint="${AZURE_OPENAI_ENDPOINT}" \
            fix-my-tests-agent
