name: Lint Markdown Files

on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    paths:
      - '**/*.md'

jobs:
  lint:
    name: Markdown Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint
        run: |
          markdownlint-cli2 --fix '**/*.md'
          markdownlint-cli2 '**/*.md'
